/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#e6f3fb',
        'on-secondary-fixed-variant': '#2e4b57',
        'tertiary-container': '#6b0008',
        'surface-tint': '#3c5d9c',
        'on-error-container': '#93000a',
        'on-secondary-container': '#4a6774',
        error: '#ba1a1a',
        'surface-container-highest': '#d7e4ec',
        'outline-variant': '#c4c6d2',
        'on-surface': '#111d23',
        'on-background': '#111d23',
        'surface-bright': '#f4faff',
        'primary-fixed': '#d8e2ff',
        secondary: '#466270',
        'surface-dim': '#cfdce4',
        'primary-fixed-dim': '#aec6ff',
        'on-primary-fixed-variant': '#224583',
        'surface-container-high': '#ddeaf2',
        'inverse-primary': '#aec6ff',
        'on-tertiary-fixed': '#410003',
        'secondary-fixed-dim': '#adcbda',
        'on-tertiary-fixed-variant': '#930010',
        'inverse-surface': '#263238',
        'error-container': '#ffdad6',
        'on-surface-variant': '#434750',
        'on-primary-fixed': '#001a42',
        surface: '#f4faff',
        'secondary-fixed': '#c9e7f7',
        'on-secondary': '#ffffff',
        primary: '#001b44',
        'on-primary-container': '#7999dc',
        'tertiary-fixed': '#ffdad6',
        'surface-container-low': '#e9f6fd',
        'surface-variant': '#d7e4ec',
        'on-secondary-fixed': '#001f2a',
        tertiary: '#430003',
        'primary-container': '#002f6c',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        background: '#f4faff',
        'secondary-container': '#c6e4f4',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#ff6960',
        'surface-container': '#e3f0f8',
        outline: '#747781',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ffb3ac',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
